apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor
  name: monitor
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    name: monitor
status:
  loadBalancer: {}
