apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: mysecret
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              key: accountname
              name: mysecret
        - name: ROLE
          value: portal
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: Portal
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: Portal-Service
        image: appddemo/adcapital-tomcat:4.4
        envFrom:
          - configMapRef:
              name: env-map
        imagePullPolicy: Always
        name: portal
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /project
          name: project
        - mountPath: /appdynamics
          name: appdynamics
      restartPolicy: Always
      imagePullPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: project
      - name: appdynamics
      initContainers:
        - image: appddemo/adcapital-project
          name: provider
          volumeMounts:
          - mountPath: /project
            name: project
status: {}
