apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: verification
  labels:
    app: verification
    name: verification
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: verification
      labels:
        app: verification
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: mysecret
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              key: accountname
              name: mysecret
        - name: ROLE
          value: verification
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: Verification
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: Verification-Service
        image: appddemo/adcapital-tomcat:latest
        envFrom:
          - configMapRef:
              name: env-map
        imagePullPolicy: Always
        name: verification
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /project
          name: project
        - mountPath: /appdynamics
          name: appdynamics
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: project
      - name: appdynamics
      initContainers:
        - image: appddemo/adcapital-project
          name: provider
          volumeMounts:
          - mountPath: /project
            name: project
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: verification
  name: verification
spec:
  ports:
  - name: "8083"
    port: 8080
    targetPort: 8083
  selector:
    app: verification
status:
  loadBalancer: {}
