apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdynamics
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
status: {}
